In [3]:
import numpy as np

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((2,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
np.eye(3)
np.linspace(0, 5, 2)
# import matplotlib.pyplot as plt
# plt.plot(np.random.rand(99,4), np.random.rand(99,4))

array([0., 5.])

In [50]:
# np.random.randn(3, 3)
np.random.randint(9)
# arr.reshape(5, 5)
# arr

7

In [10]:
lol = np.array([3,3,4,3,4,3])
lol.argmax()
lol.min()

lol = lol.reshape(3,2)
lol

array([[3, 3],
       [4, 3],
       [4, 3]])