In [2]:
import numpy as np

In [46]:
arr = np.arange(0,50)
arr[1:5]

array([1, 2, 3, 4])

In [44]:
bools = arr > 5
arr[bools]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [54]:
arr.reshape(5, 10)[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [47]:
ls = arr.copy()[2:3] = [299]
ls

[299]

In [36]:
matr = np.array([[3,2,1], [4,2,9], [4,2,93]])
matr[0,0]

3

In [35]:
matr[1:, :2]

array([[4, 2],
       [4, 2]])

In [74]:
arr2 = np.arange(0, 20)
arr2 * arr2
arr2 + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [75]:
# np.sqrt(4)
# np.sin(4)
np.max(arr2)



19

In [84]:
np.zeros((2, 4))
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])